--Dodajem tri 'default' korisnika s različitim ulogama
--Lozinka za sve racune: 1234
INSERT INTO users(username, password, enabled)
VALUES ('korisnik', '$2y$12$4PMIL20BinxS91w9F71I1OUmYcCK56i63sIL/tcmKAUFi6QGbFAGC', true),
       ('board', '$2y$12$RgKUnLWUt5/e/qRkaNflgOA6nYJJIN1nZKggnSA.WJf5UED.UpLIG', true),
       ('admin', '$2y$12$oocJTgydtJE9nyBTmcCU3..8GuKPOKxMGjM4krR/IA1VnpDPcp.Au', true);

INSERT INTO authorities(username, authority)
VALUES ('korisnik', 'ROLE_USER'),
       ('board', 'ROLE_USER'),
       ('board', 'ROLE_BOARD_MEMBER'),
       ('admin', 'ROLE_USER'),
       ('admin', 'ROLE_ADMIN');

--Random generirani obavezni podatci za student
INSERT INTO "student" (ime_student, prezime_student, mail_student, je_clan, je_aktivan_clan)
VALUES ('Nita', 'Mueller', 'Sed.nulla.ante@justofaucibus.edu', 'false', 'false'),
       ('Gloria', 'Strong', 'elit.fermentum.risus@infaucibus.edu', 'false', 'false'),
       ('Stacey', 'Grant', 'est.congue@posuerecubilia.net', 'true', 'true'),
       ('Adrian', 'Diaz', 'ante@ac.edu', 'false', 'false'),
       ('Ethan', 'Benton', 'In@liberoDonec.ca', 'false', 'false'),
       ('Jermaine', 'Wilkerson', 'convallis.est@non.edu', 'true', 'true'),
       ('Connor', 'Pruitt', 'velit.Pellentesque.ultricies@scelerisquesedsapien.org', 'true', 'false'),
       ('Diana', 'Eaton', 'non.sapien@sedsemegestas.org', 'true', 'false'),
       ('Diana', 'Britt', 'molestie.orci@Fusce.org', 'true', 'true'),
       ('Robert', 'Sellers', 'ante.Vivamus@egetmagna.edu', 'false', 'false'),
       ('Xena', 'Gaines', 'tincidunt@Nam.org', 'false', 'false'),
       ('Chandler', 'Fox', 'Nunc@aliquam.edu', 'false', 'false'),
       ('Aladdin', 'Wade', 'non.sapien.molestie@Nunclaoreet.com', 'false', 'false'),
       ('Kellie', 'Rhodes', 'ut@congue.org', 'true', 'false'),
       ('Driscoll', 'Nielsen', 'vehicula@rhoncusNullam.com', 'false', 'false'),
       ('Hasad', 'Peterson', 'vel@loremtristique.co.uk', 'false', 'false'),
       ('Diana', 'Solomon', 'a.facilisis@lorem.org', 'true', 'true'),
       ('Katell', 'Lester', 'tincidunt@aarcuSed.org', 'true', 'false'),
       ('Quamar', 'Wall', 'sociis.natoque@turpisAliquamadipiscing.ca', 'true', 'true'),
       ('Deacon', 'Sandoval', 'at.augue@venenatislacusEtiam.com', 'false', 'false'),
       ('Virginia', 'Raymond', 'convallis.dolor@mauris.org', 'false', 'false'),
       ('Peter', 'Atkins', 'ac.turpis@diam.com', 'false', 'false'),
       ('Lucas', 'Stanley', 'nibh.lacinia.orci@et.ca', 'true', 'false'),
       ('Aquila', 'Calhoun', 'ante.iaculis@atpretiumaliquet.co.uk', 'false', 'false'),
       ('Hyatt', 'Fischer', 'vel@pretiumetrutrum.org', 'false', 'false'),
       ('Teagan', 'Garza', 'facilisis@cursuseteros.edu', 'true', 'true'),
       ('Virginia', 'Finch', 'purus.gravida.sagittis@urnaNullam.co.uk', 'true', 'false'),
       ('Georgia', 'Hoffman', 'mollis.vitae@magnaaneque.co.uk', 'true', 'true'),
       ('Joshua', 'Delacruz', 'enim.gravida@tempuseu.ca', 'true', 'false'),
       ('Guy', 'Mccormick', 'Donec.nibh.enim@Donecconsectetuer.edu', 'false', 'false'),
       ('Colette', 'Marsh', 'faucibus@Integersemelit.org', 'true', 'true'),
       ('Elaine', 'Beard', 'purus@acorciUt.edu', 'false', 'false'),
       ('Henry', 'Velez', 'Morbi.vehicula.Pellentesque@Crasconvallisconvallis.org', 'false', 'false'),
       ('Gisela', 'Medina', 'ante@estacmattis.co.uk', 'false', 'false'),
       ('Jermaine', 'Duffy', 'odio.Nam.interdum@euismod.net', 'true', 'true'),
       ('Hiroko', 'Cervantes', 'placerat.eget@ligulaconsectetuer.ca', 'true', 'false'),
       ('Lucius', 'Giles', 'eu@laciniaorciconsectetuer.ca', 'false', 'false'),
       ('Reuben', 'Strickland', 'morbi@lobortis.net', 'false', 'false'),
       ('Hasad', 'Davis', 'ridiculus.mus@nunc.co.uk', 'true', 'false'),
       ('Teagan', 'Mosley', 'enim.Mauris@disparturient.co.uk', 'false', 'false'),
       ('Neville', 'Bolton', 'id.blandit.at@eratvitaerisus.co.uk', 'true', 'false'),
       ('Cooper', 'Pace', 'a.feugiat.tellus@iaculisenimsit.com', 'false', 'false'),
       ('Jenette', 'Floyd', 'vitae.orci.Phasellus@congue.ca', 'true', 'true'),
       ('Selma', 'Roach', 'at.pretium.aliquet@Integervitae.co.uk', 'false', 'false'),
       ('Chelsea', 'Jenkins', 'ipsum.primis@consectetueradipiscingelit.com', 'false', 'false'),
       ('Caryn', 'Kirk', 'fringilla@etmagnis.edu', 'true', 'true'),
       ('Carl', 'Melton', 'vulputate.risus.a@ligulaelit.co.uk', 'true', 'false'),
       ('Oprah', 'Delgado', 'orci@laciniavitae.edu', 'false', 'false'),
       ('Tucker', 'Bowers', 'aliquet.sem@DonecegestasDuis.co.uk', 'false', 'false'),
       ('Beverly', 'Cervantes', 'lacus.Aliquam.rutrum@euismodestarcu.net', 'true', 'false'),
       ('Benedict', 'Workman', 'est.vitae@consectetueradipiscingelit.com', 'true', 'true'),
       ('Burton', 'Gonzalez', 'pellentesque.tellus.sem@Pellentesque.net', 'true', 'true'),
       ('Lacy', 'Heath', 'pede@Curabitur.com', 'false', 'false'),
       ('Kennedy', 'Nielsen', 'Donec.nibh.enim@NullainterdumCurabitur.net', 'true', 'false'),
       ('Moana', 'West', 'Quisque.ornare@ipsumsodalespurus.ca', 'false', 'false'),
       ('Tucker', 'Cook', 'leo.Morbi@rutrumnon.ca', 'false', 'false'),
       ('Josiah', 'Decker', 'metus.urna.convallis@Namacnulla.com', 'false', 'false'),
       ('Brendan', 'Downs', 'rutrum.magna@mollisPhasellus.co.uk', 'true', 'true'),
       ('Lilah', 'Andrews', 'lectus.quis@nunc.edu', 'true', 'false'),
       ('Chester', 'Wynn', 'nunc.est@egestasAliquamfringilla.edu', 'false', 'false'),
       ('Haley', 'Kinney', 'Morbi.sit.amet@turpis.com', 'true', 'true'),
       ('Josiah', 'Durham', 'gravida@vitaediamProin.ca', 'true', 'false'),
       ('Aquila', 'Christensen', 'risus.Quisque@luctusetultrices.ca', 'true', 'false'),
       ('Adam', 'Russo', 'amet.risus@Donecporttitor.org', 'false', 'false'),
       ('Anne', 'Cooley', 'semper.rutrum@Aliquameratvolutpat.edu', 'false', 'false'),
       ('Fiona', 'Atkinson', 'eu.dui.Cum@tincidunt.org', 'false', 'false'),
       ('Lavinia', 'Alvarado', 'rutrum.magna.Cras@porttitorscelerisqueneque.edu', 'true', 'true'),
       ('Axel', 'Warren', 'Duis@milorem.edu', 'true', 'true'),
       ('Gage', 'Jackson', 'morbi@metusfacilisis.edu', 'false', 'false'),
       ('Bert', 'Melendez', 'lectus@interdum.com', 'true', 'false'),
       ('Orla', 'Carrillo', 'aliquet.lobortis@aliquet.co.uk', 'false', 'false'),
       ('Ethan', 'Michael', 'neque@insodaleselit.org', 'false', 'false'),
       ('William', 'Richmond', 'Nullam.velit@lobortisClassaptent.edu', 'false', 'false'),
       ('Alexa', 'Sweeney', 'tellus@Ut.org', 'true', 'true'),
       ('Quamar', 'Tran', 'sociis.natoque.penatibus@Vestibulumante.com', 'false', 'false'),
       ('Sonya', 'Mckenzie', 'nisi.Mauris.nulla@libero.ca', 'true', 'false'),
       ('Dane', 'Salas', 'eu.erat@dictum.net', 'true', 'false'),
       ('Hall', 'Martin', 'lacus.Quisque@atiaculisquis.com', 'false', 'false'),
       ('Aretha', 'Mcgee', 'mi@etnetuset.org', 'true', 'false'),
       ('Bertha', 'Mosley', 'est.Nunc@aliquetodio.ca', 'false', 'false'),
       ('Patience', 'Caldwell', 'purus.in.molestie@a.net', 'false', 'false'),
       ('Kylee', 'Foster', 'eu@vestibulumMaurismagna.net', 'false', 'false'),
       ('Castor', 'Blackburn', 'massa.non@magna.org', 'false', 'false'),
       ('Hedwig', 'Wade', 'arcu@mattissemper.org', 'true', 'true'),
       ('Fuller', 'Pratt', 'Proin@ametconsectetueradipiscing.net', 'false', 'false'),
       ('Davis', 'Burks', 'nec.ligula@magnaPhasellus.org', 'true', 'true'),
       ('Miranda', 'Hendricks', 'pulvinar.arcu@tortorat.com', 'true', 'false'),
       ('Robert', 'Wallace', 'lorem.fringilla@Sed.edu', 'false', 'false'),
       ('Hillary', 'Carpenter', 'sagittis.semper@odio.net', 'false', 'false'),
       ('Whitney', 'Nixon', 'vehicula.aliquet@insodaleselit.ca', 'false', 'false'),
       ('Darius', 'Ramos', 'neque.pellentesque.massa@nuncid.com', 'false', 'false'),
       ('Aristotle', 'Lester', 'ligula.consectetuer.rhoncus@consequat.co.uk', 'false', 'false'),
       ('Len', 'Herrera', 'eu.tellus@Curabitursedtortor.ca', 'true', 'true'),
       ('Quemby', 'Walls', 'vitae@mus.co.uk', 'true', 'true'),
       ('Rose', 'Blackburn', 'Aenean.massa@elitpellentesquea.edu', 'false', 'false'),
       ('Selma', 'Douglas', 'mauris.erat@mienim.net', 'false', 'false'),
       ('Cathleen', 'Chandler', 'vulputate@Vivamus.net', 'true', 'false'),
       ('Colt', 'Herman', 'dui.Fusce@nuncinterdumfeugiat.org', 'false', 'false'),
       ('Anjolie', 'Whitney', 'purus.ac@CraspellentesqueSed.org', 'true', 'false'),
       ('Denise', 'Spencer', 'tincidunt.aliquam.arcu@Crassed.co.uk', 'false', 'false');